language: c
addons:
  apt:
    packages:
      - jq
  homebrew:
    packages:
      - jq
    update: true
script: asdf plugin-test osctl $TRAVIS_BUILD_DIR 'osctl'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
